### ISSUE TITLE
Debug Grid rotation and misalignment

### ISSUE THREAD

**Issue by cod3m0nk** [CaptainCoderOrg/CapMan#24]
I am experiencing an issue with the debug grid not displaying correctly when running the game. The grid appears rotated and positioned outside the game area:

![DebugGrid](https://github.com/CaptainCoderOrg/CapMan/assets/75347870/d6c2fe68-8ea5-4ba8-b485-ea132ab78fc8)

Steps to Reproduce:
1. Launch the game.
2. Activate the debug grid pressing `g`.
3. Observe that the debug grid is displayed rotated and positioned outside the game area.

Expected Behavior:
The debug grid should be properly aligned within the game area, providing an accurate representation of the board for debugging purposes.

Additional Information:
I am currently running the game on **Linux**, which may be causing the observed issue. It is possible that there might be an incompatibility that makes Raylib work differently on Linux. If someone can confirm that the issue can be reproduced on **Windows** builds that would be great.

**Comment by jcollard** [comment]
I can confirm this is happening on my build as well. Thank you for reporting this.
