### ISSUE TITLE
Add More Tests

### ISSUE THREAD

**Issue by DerekGooding** [CaptainCoderOrg/CapMan#45]
Coverage is low. Create more tests for existing methods and codebase.

**Comment by DerekGooding** [comment]
Fair. You mentioned it on stream but I made a poor go at the specifics.

**Comment by jcollard** [comment]
Perhaps this Issue could be rewritten as a task to provide test coverage statistics on build? Then, we would have a better idea of where we should focus tests.

**Comment by DerekGooding** [comment]
Now you know why I was asking you about how you felt about test coverage on stream. You seemed against it. But yes, I'm down with this as a first step. I'll add a new issue to capture this idea.
