### ISSUE TITLE
Add Test Coverage

### ISSUE THREAD

**Issue by DerekGooding** [CaptainCoderOrg/CapMan#63]
Add some form of test coverage automation so we can identify what parts of the codebase aren't being tested. 

Then we can create issues based on what tests are needed. 

This closes #45

**Comment by jcollard** [comment]
This can now be done using the following commands:

```
dotnet test -p:CollectCoverage=true -p:CoverletOutputFormat=cobertura
reportgenerator -reports:CapMan.Tests/coverage.cobertura.xml  -targetdir:html-coverage-report/
```

You may need to install Report Generator: https://github.com/danielpalme/ReportGenerator

This can be done globally: `dotnet tool install -g dotnet-reportgenerator-globaltool`
